table 'Measures setup'
	isHidden
	lineageTag: d60314d0-d319-4f3b-b80c-6d43b34bb778

	measure 'Selected setup' = SELECTEDVALUE('Measures setup'[Setup])
		isHidden
		lineageTag: ff2a11a3-1d28-4a0f-8760-fa56e21a36ef

		changedProperty = IsHidden

	column Setup
		dataType: string
		isHidden
		lineageTag: cf5b3089-35ef-4153-8cf7-bfb6ff201838
		summarizeBy: none
		sourceColumn: Setup

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Measures setup' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCkpNL81JLFKK1YlWci4tLlEoLkhNzkzLTFaKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Setup = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Setup", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

